-- ============================================================
-- SNOWFLAKE OPTIMIZATION, SECURITY & GOVERNANCE
-- ============================================================

-- ──────────────────────────────────────
-- 1. WAREHOUSE SIZING & AUTO-SUSPEND
-- ──────────────────────────────────────
CREATE OR REPLACE WAREHOUSE ETL_WH
    WAREHOUSE_SIZE   = 'LARGE'
    AUTO_SUSPEND     = 120          -- Suspend after 2 min idle
    AUTO_RESUME      = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 4           -- Multi-cluster for concurrency
    SCALING_POLICY   = 'ECONOMY'
    COMMENT = 'ETL pipeline warehouse';

CREATE OR REPLACE WAREHOUSE ANALYTICS_WH
    WAREHOUSE_SIZE   = 'MEDIUM'
    AUTO_SUSPEND     = 300
    AUTO_RESUME      = TRUE
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY   = 'STANDARD'
    COMMENT = 'Analyst query warehouse';

CREATE OR REPLACE WAREHOUSE REPORTING_WH
    WAREHOUSE_SIZE   = 'XSMALL'
    AUTO_SUSPEND     = 60
    AUTO_RESUME      = TRUE
    COMMENT = 'Dashboard / BI reporting - always small';


-- ──────────────────────────────────────
-- 2. CLUSTERING KEYS
-- ──────────────────────────────────────
-- Cluster FACT_FLIGHT on most common filter predicates
ALTER TABLE FACT_FLIGHT
    CLUSTER BY (DATE_KEY, AIRLINE_KEY);

-- Monitor clustering state
SELECT SYSTEM$CLUSTERING_INFORMATION('FACT_FLIGHT', '(DATE_KEY, AIRLINE_KEY)');

-- Cluster reservations
ALTER TABLE FACT_RESERVATION
    CLUSTER BY (DATE_KEY, PASSENGER_KEY);

-- Enable automatic reclustering
ALTER TABLE FACT_FLIGHT    RESUME RECLUSTER;
ALTER TABLE FACT_RESERVATION RESUME RECLUSTER;


-- ──────────────────────────────────────
-- 3. SEARCH OPTIMIZATION (micro-partition pruning)
-- ──────────────────────────────────────
ALTER TABLE DIM_PASSENGER
    ADD SEARCH OPTIMIZATION ON EQUALITY(PASSENGER_ID, EMAIL, FREQUENT_FLYER_NUM);

ALTER TABLE FACT_FLIGHT
    ADD SEARCH OPTIMIZATION ON EQUALITY(FLIGHT_NUMBER, TAIL_NUMBER);

ALTER TABLE FACT_RESERVATION
    ADD SEARCH OPTIMIZATION ON EQUALITY(BOOKING_REF, TICKET_NUMBER);


-- ──────────────────────────────────────
-- 4. DYNAMIC TABLES (ELT materialization)
-- ──────────────────────────────────────
CREATE OR REPLACE DYNAMIC TABLE DT_DAILY_AIRLINE_PERFORMANCE
    TARGET_LAG = '1 hour'
    WAREHOUSE  = ETL_WH
AS
SELECT
    d.FULL_DATE,
    d.YEAR,
    d.MONTH_NUM,
    d.MONTH_NAME,
    a.AIRLINE_CODE,
    a.AIRLINE_NAME,
    COUNT(*)                                          AS TOTAL_FLIGHTS,
    SUM(IFF(IS_CANCELLED, 1, 0))                      AS CANCELLED,
    SUM(IFF(ARR_DELAY_MIN > 15 AND NOT IS_CANCELLED, 1, 0)) AS DELAYED,
    ROUND(AVG(ARR_DELAY_MIN), 2)                      AS AVG_ARR_DELAY,
    ROUND(AVG(DEP_DELAY_MIN), 2)                      AS AVG_DEP_DELAY,
    ROUND(SUM(TOTAL_REVENUE), 2)                      AS TOTAL_REVENUE,
    ROUND(AVG(LOAD_FACTOR), 4)                        AS AVG_LOAD_FACTOR,
    ROUND(100.0 * SUM(IFF(ARR_DELAY_MIN <= 15 AND NOT IS_CANCELLED, 1, 0))
              / NULLIF(COUNT(*), 0), 2)               AS ON_TIME_PCT
FROM FACT_FLIGHT  F
JOIN DIM_DATE     D ON F.DATE_KEY    = D.DATE_KEY
JOIN DIM_AIRLINE  A ON F.AIRLINE_KEY = A.AIRLINE_KEY
GROUP BY 1,2,3,4,5,6;


-- ──────────────────────────────────────
-- 5. SEMI-STRUCTURED DATA (VARIANT)
-- ──────────────────────────────────────
-- Store raw JSON flight events in Snowflake VARIANT column
CREATE OR REPLACE TABLE RAW_FLIGHT_EVENTS (
    EVENT_ID        STRING       NOT NULL,
    EVENT_TS        TIMESTAMP_NTZ NOT NULL,
    SOURCE_SYSTEM   STRING,
    PAYLOAD         VARIANT,      -- Raw JSON blob
    LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Flatten VARIANT for analysis
CREATE OR REPLACE VIEW VW_FLIGHT_EVENTS_FLAT AS
SELECT
    EVENT_ID,
    EVENT_TS,
    PAYLOAD:flightNumber::STRING    AS FLIGHT_NUMBER,
    PAYLOAD:airline::STRING         AS AIRLINE_CODE,
    PAYLOAD:origin::STRING          AS ORIGIN,
    PAYLOAD:destination::STRING     AS DESTINATION,
    PAYLOAD:status::STRING          AS STATUS,
    PAYLOAD:delays.carrier::INT     AS CARRIER_DELAY,
    PAYLOAD:delays.weather::INT     AS WEATHER_DELAY,
    PAYLOAD:delays.nas::INT         AS NAS_DELAY,
    PAYLOAD:position.lat::FLOAT     AS LATITUDE,
    PAYLOAD:position.lon::FLOAT     AS LONGITUDE,
    PAYLOAD:position.altitude::INT  AS ALTITUDE_FT,
    -- Explode nested passenger array
    VALUE:passengerId::STRING       AS PASSENGER_ID,
    VALUE:cabin::STRING             AS CABIN_CLASS
FROM RAW_FLIGHT_EVENTS,
     LATERAL FLATTEN(INPUT => PAYLOAD:passengers) p;


-- ──────────────────────────────────────
-- 6. TIME TRAVEL & DATA RECOVERY
-- ──────────────────────────────────────

-- Query table as it was 24 hours ago
SELECT COUNT(*) FROM FACT_FLIGHT
AT (OFFSET => -86400);   -- 24h in seconds

-- Restore accidentally deleted rows
INSERT INTO FACT_FLIGHT
SELECT * FROM FACT_FLIGHT
AT (TIMESTAMP => '2024-12-01 08:00:00'::TIMESTAMP)
WHERE DATE_KEY = 20241201
MINUS
SELECT * FROM FACT_FLIGHT
WHERE DATE_KEY = 20241201;

-- Clone table for testing (zero-copy)
CREATE OR REPLACE TABLE FACT_FLIGHT_TEST
    CLONE FACT_FLIGHT
    AT (OFFSET => -3600);   -- Clone as of 1 hour ago

-- Data retention settings
ALTER TABLE FACT_FLIGHT     SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE FACT_RESERVATION SET DATA_RETENTION_TIME_IN_DAYS = 90;
ALTER TABLE DIM_PASSENGER    SET DATA_RETENTION_TIME_IN_DAYS = 365;


-- ──────────────────────────────────────
-- 7. RBAC — ROLES & PRIVILEGES
-- ──────────────────────────────────────

-- Create role hierarchy
CREATE ROLE IF NOT EXISTS AIRLINE_ADMIN;
CREATE ROLE IF NOT EXISTS AIRLINE_ANALYST;
CREATE ROLE IF NOT EXISTS AIRLINE_READER;
CREATE ROLE IF NOT EXISTS ETL_ROLE;
CREATE ROLE IF NOT EXISTS DATA_STEWARD;

-- Grant role hierarchy (child → parent)
GRANT ROLE AIRLINE_READER  TO ROLE AIRLINE_ANALYST;
GRANT ROLE AIRLINE_ANALYST TO ROLE AIRLINE_ADMIN;
GRANT ROLE DATA_STEWARD    TO ROLE AIRLINE_ADMIN;

-- ETL Role: write to all tables
GRANT USAGE ON WAREHOUSE ETL_WH TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE AIRLINE_DW TO ROLE ETL_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRLINE_DW TO ROLE ETL_ROLE;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN DATABASE AIRLINE_DW TO ROLE ETL_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE AIRLINE_DW TO ROLE ETL_ROLE;

-- Analyst Role: read + run queries
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE AIRLINE_ANALYST;
GRANT USAGE ON DATABASE AIRLINE_DW TO ROLE AIRLINE_ANALYST;
GRANT SELECT ON ALL TABLES   IN SCHEMA AIRLINE_DW.PUBLIC TO ROLE AIRLINE_ANALYST;
GRANT SELECT ON ALL VIEWS    IN SCHEMA AIRLINE_DW.PUBLIC TO ROLE AIRLINE_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA AIRLINE_DW.PUBLIC TO ROLE AIRLINE_ANALYST;

-- Reader Role: BI dashboards only
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE AIRLINE_READER;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA AIRLINE_DW.PUBLIC TO ROLE AIRLINE_READER;
GRANT SELECT ON ALL VIEWS IN SCHEMA AIRLINE_DW.PUBLIC TO ROLE AIRLINE_READER;

-- Assign users to roles
GRANT ROLE ETL_ROLE        TO USER svc_etl_prod;
GRANT ROLE AIRLINE_ANALYST TO USER john_analyst;
GRANT ROLE AIRLINE_READER  TO USER dashboard_svc;
GRANT ROLE AIRLINE_ADMIN   TO USER dba_admin;


-- ──────────────────────────────────────
-- 8. DATA MASKING (Column-Level Security)
-- ──────────────────────────────────────

-- PII masking policy for passenger email
CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (VAL STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AIRLINE_ADMIN', 'DATA_STEWARD') THEN VAL
        WHEN CURRENT_ROLE() = 'AIRLINE_ANALYST'
            THEN REGEXP_REPLACE(VAL, '(.{2})(.+)(@.+)', '\\1****\\3')  -- jo****@email.com
        ELSE '***MASKED***'
    END;

CREATE OR REPLACE MASKING POLICY MASK_PHONE AS (VAL STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('AIRLINE_ADMIN', 'DATA_STEWARD') THEN VAL
        ELSE CONCAT('***-***-', RIGHT(VAL, 4))
    END;

CREATE OR REPLACE MASKING POLICY MASK_DOB AS (VAL DATE)
RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('AIRLINE_ADMIN', 'DATA_STEWARD') THEN VAL
        ELSE DATE_TRUNC('YEAR', VAL)   -- Only show birth year
    END;

-- Apply masking policies
ALTER TABLE DIM_PASSENGER MODIFY COLUMN EMAIL  SET MASKING POLICY MASK_EMAIL;
ALTER TABLE DIM_PASSENGER MODIFY COLUMN PHONE  SET MASKING POLICY MASK_PHONE;
ALTER TABLE DIM_PASSENGER MODIFY COLUMN DOB    SET MASKING POLICY MASK_DOB;

-- Ticket/price masking for reader role
CREATE OR REPLACE MASKING POLICY MASK_FARE AS (VAL NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('AIRLINE_ADMIN', 'AIRLINE_ANALYST') THEN VAL
        ELSE NULL
    END;

ALTER TABLE FACT_RESERVATION MODIFY COLUMN TOTAL_FARE SET MASKING POLICY MASK_FARE;


-- ──────────────────────────────────────
-- 9. ROW ACCESS POLICIES (Row-Level Security)
-- ──────────────────────────────────────

-- Analysts only see data for their assigned airline(s)
CREATE OR REPLACE TABLE USER_AIRLINE_ACCESS (
    USERNAME        STRING,
    AIRLINE_CODE    STRING
);

CREATE OR REPLACE ROW ACCESS POLICY RAP_AIRLINE_FILTER
AS (AIRLINE_CODE STRING) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('AIRLINE_ADMIN', 'ETL_ROLE')  -- Admins see all
    OR EXISTS (
        SELECT 1 FROM USER_AIRLINE_ACCESS
        WHERE USERNAME    = CURRENT_USER()
          AND AIRLINE_CODE = AIRLINE_CODE
    );

ALTER TABLE FACT_FLIGHT
    ADD ROW ACCESS POLICY RAP_AIRLINE_FILTER ON (AIRLINE_KEY);


-- ──────────────────────────────────────
-- 10. QUERY GOVERNANCE & TAGGING
-- ──────────────────────────────────────

-- Create PII tag
CREATE OR REPLACE TAG PII_SENSITIVITY
    ALLOWED_VALUES 'HIGH', 'MEDIUM', 'LOW', 'NONE';

-- Tag PII columns
ALTER TABLE DIM_PASSENGER MODIFY COLUMN EMAIL  SET TAG PII_SENSITIVITY = 'HIGH';
ALTER TABLE DIM_PASSENGER MODIFY COLUMN PHONE  SET TAG PII_SENSITIVITY = 'HIGH';
ALTER TABLE DIM_PASSENGER MODIFY COLUMN DOB    SET TAG PII_SENSITIVITY = 'MEDIUM';
ALTER TABLE FACT_RESERVATION MODIFY COLUMN TOTAL_FARE SET TAG PII_SENSITIVITY = 'LOW';

-- Resource monitors to prevent runaway queries
CREATE OR REPLACE RESOURCE MONITOR ANALYST_BUDGET
    WITH CREDIT_QUOTA = 500          -- 500 credits/month
    FREQUENCY = MONTHLY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 90 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE ANALYTICS_WH SET RESOURCE_MONITOR = ANALYST_BUDGET;

-- Query profiling & cost attribution
ALTER SESSION SET QUERY_TAG = 'DASHBOARD_RENDER';
SELECT QUERY_ID, QUERY_TAG, CREDITS_USED_CLOUD_SERVICES, EXECUTION_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME > DATEADD('hour', -24, CURRENT_TIMESTAMP())
  AND QUERY_TAG != ''
ORDER BY CREDITS_USED_CLOUD_SERVICES DESC;
